routes/web.php
<?php

use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/reports');
});

Route::middleware(['auth'])->namespace('App\Http\Controllers')->group(function () {
    //homepage (form for managers)
    //report
    Route::get('reports', 'ReportController@index');
    Route::post('store-report', 'ReportController@store');
    Route::get('details/{report}', 'ReportController@details')->name('report-details');
    Route::get('create-report/', 'ReportController@create');
    Route::get('edit-report/{report}', 'ReportController@edit');
    Route::post('update-report/{report}', 'ReportController@update');
    Route::get('delete-report/{report}', 'ReportController@delete');
    Route::get('submit/{report}', 'ReportController@submit');
    Route::get('print-report/{report}', 'ReportController@print');
    Route::get('print-certificates/{report}', 'ReportController@printCertificates');
    Route::post('clone-report/{report}', 'ReportController@cloneReport');

    //report-item
    Route::post('store-report-item/{report}', 'ReportItemController@storeReportItem');
    Route::get('edit-report-item/{reportItem}', 'ReportItemController@editReportItem');
    Route::post('update-report-item/{reportItem}', 'ReportItemController@updateReportItem');
    Route::get('delete-report-item/{reportItem}', 'ReportItemController@deleteReportItem');
    Route::get('get-report-items/{value}/{type}/', 'ReportItemController@getReportItems');
    Route::post('add-report-items/{report}', 'ReportItemController@addReportItems')->name('add-report-items');
    Route::post('find-report-item', 'ReportItemController@findReportItem')->name('find-report-item');
});

Route::middleware(['auth'])->namespace('App\Http\Controllers\Admin')->group(function () {
    //admin side
    Route::get('admin', 'ReportsController@index');
    Route::resource('admin/roles', 'RolesController');
    Route::resource('admin/permissions', 'PermissionsController');
    Route::resource('admin/users', 'UsersController');
    Route::resource('admin/activitylogs', 'ActivityLogsController');
    Route::resource('admin/reports', 'ReportsController');
    Route::put('admin/reports/restore/{report}', 'ReportsController@restore');
    Route::get('admin/reports/{report}/print', 'ReportsController@print');
    Route::get('admin/reports/print-certificates/{report}', 'ReportsController@printCertificates');
    Route::resource('admin/report-items', 'ReportItemsController');
    Route::put('admin/report-items/restore/{report}', 'ReportItemsController@restore');
    Route::resource('admin/customers', 'CustomersController');

    //developer tools
    Route::get('admin/generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@getGenerator']);
    Route::post('admin/generator', ['uses' => '\Appzcoder\LaravelAdmin\Controllers\ProcessController@postGenerator']);
});

Auth::routes();

app/Models/Report.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;
use Spatie\Activitylog\Traits\LogsActivity;

class Report extends Model
{
    use LogsActivity, SoftDeletes, Notifiable;

    const STATUS_CREATING = 0;
    const STATUS_SUBMITTED = 1;

    const TYPE_SERVICE = 'service';
    const TYPE_RECEIVER = 'receiver';

    const PER_PAGE = 25;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'reports';

    /**
     * The database primary key value.
     *
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = [
        'customer',
        'client',
        'owner',
        'rcvd_date',
        'wash_date',
        'number_type',
        'inspector',
        'off_lease',
        'notes',
    ];

    protected $dates = ['rcvd_date', 'wash_date'];

    public function items()
    {
        $relation = $this->hasMany(ReportItem::class);
        if (Auth::user()->hasRole('admin')) {
            $relation->withTrashed();
        }

        return $relation;
    }

    public function reporter()
    {
        return $this->belongsTo(User::class, 'reporter_id', 'id');
    }

    /**
     * @return string
     */
    public function getNumberAttribute(): string
    {
        if ($this->number_type == self::TYPE_SERVICE) {
            $prefix = 'S';
        } else {
            $prefix = 'R';
        }
        return $prefix . (10000 + $this->id);
    }

    /**
     * Change activity log event description
     *
     * @param string $eventName
     *
     * @return string
     */
    public function getDescriptionForEvent($eventName)
    {
        return __CLASS__ . " model has been {$eventName}";
    }
}

app/Models/ReportItem.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Spatie\Activitylog\Traits\LogsActivity;

class ReportItem extends Model
{
    use LogsActivity, SoftDeletes;

    const WASH_TYPES = ['n/a' => 'N/A', 'detergent' => 'Detergent Wash', 'solvent' => 'Solvent Wash', ];

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'report_items';

    /**
     * The database primary key value.
     *
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = [
        'manufacturer',
        'serial_number',
        'unit_number',
        'qd',
        '5yt',
        'mfr_date',
        'ret_date',
        'dot_un',
        'size',
        'bc',
        'materials_of_construction',
        'origin_report_id',
        'updated_at',
        'comments',
    ];

    protected $casts = ['comments' => 'json'];

    protected $dates = ['mfr_date', 'ret_date', '5yt'];

    public function get5yt()
    {
        return $this->attributes['5yt'] ? Carbon::parse($this->attributes['5yt']) : null;
    }

    public function setMfrDateAttribute($value)
    {
        $this->attributes['mfr_date'] = $this->parseDate($value);
    }

    public function setRetDateAttribute($value)
    {
        $this->attributes['ret_date'] = $this->parseDate($value);
    }

    public function set5ytAttribute($value)
    {
        $this->attributes['5yt'] = $this->parseDate($value);
    }

    public function report()
    {
        $relation = $this->belongsTo(Report::class);
        if (Auth::user()->hasRole('admin')) {
            $relation->withTrashed();
        }

        return $relation;
    }

    public static function getCommentsFields()
    {
        return [
            'wash_type'  => 'Wash Type',
            'test'  => 'Test (30 mo)',
            'test_date'  => 'Date (30 mo)',
            'has_5yt'  => '5YT',
            '5yt'  => 'Date (5YT)',
            'thickness'  => 'Thickness',
            '2opw' => '2"OPW',
            '2epdm' => '2"EPDM',
            '3epdm' => '3"EPDM',
            'multiseal' => 'Multiseal',
            'opw'   => 'Polyvent',
            'elbow_nipple'  => 'Elbow',
            'nipple'  => 'Nipple',
            'ring'  => 'Ring',
            'nut_bolt'  => 'Nut/Bolt',
            'ss_bung'  => 'SS Bung',
            'part_f'  => 'Part F',
            'cables'  => 'Cables',
            'decals'  => 'Decals',
            'valve'  => 'Valve',
            'valve_lab'  => 'Valve Labor',
            'valve_cap'  => 'Valve CAP',
            'retape'  => 'Retape',
            'ex_cleaning'  => 'Ex Cleaning Labor (hours)',
            'welds'  => 'Welds (min)',
            'guard'  => 'Weld @ guard',
            'leg'  => 'Weld @ leg',
            'outlet'  => 'Weld @ outlet',
            'ai_proof_test' => 'Air-leak Proof Test',
            'passivation' => 'Passivation',
            'new_lid' => 'New lid',
            'new_girard' => 'New Girard',
            'barcoded' => 'Barcoded',
            'leak_proof_test' => 'Leak Proof Test',
            'five_in_one_git' => '5in1 Git',
            'external_inspection' => 'External Inspection',
            'internal_inspection' => 'Internal Inspection',
            'min_wall_thickness_test' => 'Min Wall Thickness Test',
            'notes' => 'Additional Notes',
        ];
    }

    /**
     * Change activity log event description
     *
     * @param string $eventName
     *
     * @return string
     */
    public function getDescriptionForEvent($eventName)
    {
        return __CLASS__ . " model has been {$eventName}";
    }

    public function getOriginReportNumberAttribute(): string
    {
        $prefix = '';

        return $this->attributes['origin_report_id'] ? $prefix . (10000 + $this->attributes['origin_report_id']) : '';
    }

    public function getQdLabelAttribute() {
        return $this->qd == 1 ? 'Y' : 'N';
    }

    public function getHasCertificateAttribute(): bool {
        return (!empty($this->comments['test']) && $this->comments['test'] == 1)
            || (!empty($this->comments['has_5yt']) && $this->comments['has_5yt'] == 1);
    }

    protected function parseDate($value): ?string
    {
        if(empty($value)) return null;

        $result = null;
        try {
            $result = Carbon::parse($value)->format('Y-m-d');
        } catch (\Throwable $e) {}

        if(!$result) {
            try {
                $result = Carbon::createFromFormat('m/Y', $value)->format('Y-m-d');
            } catch (\Throwable $e) {}
        }

        return $result;
    }
}

app/Http/Controllers/Admin/ReportsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Client;
use App\Models\Customer;
use App\Models\Report;
use App\Services\ReportService;
use Illuminate\Http\Request;

class ReportsController extends AdminController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index(Request $request, ReportService $reportService)
    {
        $reports = $reportService->search($request->get('search'));

        return view('admin.reports.index', compact('reports'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function show(int $id, ReportService $reportService)
    {
        $report = Report::withTrashed()->findOrFail($id);
        $itemsTotal = $reportService->totalItemsData($report);

        return view('admin.reports.show', compact('report', 'itemsTotal'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function edit(int $id, ReportService $reportService)
    {
        $report = Report::withTrashed()->findOrFail($id);
        $reportService->tryAccess($report, auth()->user());
        $customers = Customer::all();
        $clients = Client::all();

        return view('admin.reports.edit', compact('report', 'customers', 'clients'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(int $id, Request $request, ReportService $reportService)
    {
        $report = Report::withTrashed()->findOrFail($id);
        $reportService->tryAccess($report, auth()->user());
        $reportService->updateFromRequest($report, $request);

        return redirect('admin/reports')->with('flash_message', 'Report updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        Report::destroy($id);

        return redirect('admin/reports')->with('flash_message', 'Report deleted!');
    }

    public function print(int $id, ReportService $reportService)
    {
        $report = Report::withTrashed()->with(['reporter', 'items'])->findOrFail($id);
        $itemsTotal = collect($reportService->totalItemsData($report));

        return view('admin.reports.print', compact('report', 'itemsTotal'));
    }

    public function printCertificates(int $id, ReportService $reportService)
    {
        $report = Report::withTrashed()->with(['reporter', 'items'])->findOrFail($id);
        $itemsTotal = collect($reportService->totalItemsData($report));

        return view('admin.reports.print-certificates', compact('report', 'itemsTotal'));
    }

    public function restore(int $id)
    {
        Report::onlyTrashed()->findOrFail($id)->restore();

        return redirect('/admin/reports/' . $id)->with('flash_message', 'A report has been restored.');
    }
}

resources/views/admin/reports/create.blade.php
@extends('layouts.backend')

@section('content')
    <div class="container-fluid">
        <div class="row">
            @include('admin.sidebar')

            <div class="col-lg-10 col-md-9">
                <div class="card">
                    <div class="card-header">Create New Report</div>
                    <div class="card-body">
                        <a href="{{ url('/admin/reports') }}" title="Back"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
                        <br />
                        <br />

                        @if ($errors->any())
                            <ul class="alert alert-danger">
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        @endif

                        {!! Form::open(['url' => '/admin/reports', 'class' => 'form-horizontal', 'files' => true]) !!}

                        @include ('admin.reports.form', ['formMode' => 'create'])

                        {!! Form::close() !!}

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/reports/edit.blade.php
@extends('layouts.backend')

@section('content')
  <div class="container-fluid">
    <div class="row">
      @include('admin.sidebar')

      <div class="col-lg-10">
        <div class="card">
          <div class="card-header">Edit Report: {{ $report->number }}</div>
          <div class="card-body">
            <a href="{{ url('/admin/reports') }}" title="Back"><button class="btn btn-warning btn-sm"><i
                  class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
            <br />
            <br />

            @if ($errors->any())
              <ul class="alert alert-danger">
                @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
                @endforeach
              </ul>
            @endif

            {!! Form::model($report, [
                'method' => 'PATCH',
                'url' => ['/admin/reports', $report->id],
                'class' => 'form-horizontal',
                'files' => true,
            ]) !!}

            @include ('admin.reports.form', ['formMode' => 'edit', 'model' => $report])

            {!! Form::close() !!}

          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/admin/reports/index.blade.php
@extends('layouts.backend')

@section('content')
  <div class="container-fluid">
    <div class="row">
      @include('admin.sidebar')

      <div class="col-lg-10">
        <div class="card">
          <div class="card-header">Reports</div>
          <div class="card-body">

            {!! Form::open(['method' => 'GET', 'url' => '/admin/reports', 'class' => 'form-inline my-2 my-lg-0 float-right', 'role' => 'search']) !!}
            <div class="input-group">
              <input type="text" class="form-control" name="search" placeholder="Search..."
                value="{{ request('search') }}">
              <span class="input-group-append">
                <button class="btn btn-secondary" type="submit">
                  <i class="fa fa-search"></i>
                </button>
              </span>
            </div>
            {!! Form::close() !!}
            <br />
            <br />

            <div class="table-responsive">
              <table class="table table-striped reports-table">
                <thead>
                  <tr>
                    <th>{{ __('Number') }}</th>
                    <th>{{ __('Manager') }}</th>
                    <th>{{ __('Customer') }}</th>
                    <th>{{ __('Bill to') }}</th>
                    <th>{{ __('Rcv\'d Date') }}</th>
                    <th>{{ __('Service Date') }}</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  @foreach ($reports as $item)
                    <tr class="{{ $item->trashed() ? 'reports-table__trash-row' : '' }}">
                      <td>{{ $item->number }}</td>
                      <td><a href="/admin/users/{{ $item->reporter_id }}">{{ $item->reporter->name }}</a></td>
                      <td>{{ $item->customer }}</td>
                      <td>{{ $item->client }}</td>
                      <td>{{ $item ? $item->rcvd_date->format('m/d/Y') : '---' }}</td>
                      <td>{{ $item ? $item->wash_date->format('m/d/Y') : '---' }}</td>

                      <td class="actions text-right">
                        @if($item->number_type === $item::TYPE_SERVICE)
                          <div class="btn-group">
                            <button type="button" class="btn btn-outline-success btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <i class="fa fa-print" aria-hidden="true"></i>
                            </button>
                            <div class="dropdown-menu">
                              <a class="dropdown-item" target="_blank" href="{{ url('/admin/reports/' . $item->id .'/print') }}">Full Report</a>
                              <a class="dropdown-item" target="_blank" href="{{ url('/admin/reports/' . $item->id) . '/print?onlypartsservice=true' }}">Only Parts & Service</a>
                              <a class="dropdown-item" target="_blank" href="{{ url('/admin/reports/' . $item->id) . '/print?onlytotalsservice=true' }}">Only Parts & Service Totals</a>
                              <a class="dropdown-item" target="_blank" href="{{ url('/admin/reports/print-certificates/' . $item->id) }}">Certifications</a>
                            </div>
                          </div>
                        @else
                          <a target="_blank" href="{{ url('/admin/reports/' . $item->id .'/print') }}" title="Print Report"><button
                              class="btn btn-outline-success btn-sm"><i class="fa fa-print" aria-hidden="true"></i></button></a>
                        @endif
                        <a href="{{ url('/admin/reports/' . $item->id) }}" title="View Report"><button
                            class="btn btn-outline-info btn-sm"><i class="fa fa-eye" aria-hidden="true"></i></button></a>
                        <a href="{{ url('/admin/reports/' . $item->id . '/edit') }}" title="Edit Report"><button
                            class="btn btn-primary btn-sm"><i class="fa fa-edit" aria-hidden="true"></i></button></a>
                        @if($item->trashed())
                            {!! Form::open([
                              'method' => 'PUT',
                              'url' => ['/admin/reports/restore', $item->id],
                              'style' => 'display:inline',
                          ]) !!}
                            {!! Form::button('<i class="fas fa-trash-restore-alt" aria-hidden="true"></i>', [
                                'type' => 'submit',
                                'class' => 'btn btn-outline-danger btn-sm',
                                'title' => 'Restore Report',
                                'onclick' => 'return confirm("Restore Report?")',
                            ]) !!}
                            {!! Form::close() !!}
                        @else
                          {!! Form::open([
                              'method' => 'DELETE',
                              'url' => ['/admin/reports', $item->id],
                              'style' => 'display:inline',
                          ]) !!}
                          {!! Form::button('<i class="fa fa-trash" aria-hidden="true"></i>', [
                              'type' => 'submit',
                              'class' => 'btn btn-danger btn-sm',
                              'title' => 'Delete Report',
                              'onclick' => 'return confirm("Confirm delete?")',
                          ]) !!}
                          {!! Form::close() !!}
                        @endif
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
              <div class="pagination-wrapper"> {!! $reports->appends(['search' => Request::get('search')])->render() !!} </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/admin/reports/show.blade.php
@extends('layouts.backend')

@section('content')
  <div class="container-fluid report-item-print">
    <div class="row">
      @include('admin.sidebar')

      <div class="col-lg-10">
        <div class="card">
          <div class="card-header">Report {{ $report->number }}</div>
          <div class="card-body">

            <a href="{{ url('/admin/reports') }}" title="Back"><button class="btn btn-warning btn-sm"><i
                  class="fa fa-arrow-left" aria-hidden="true"></i> Back</button></a>
            <a href="{{ url('/admin/reports/' . $report->id . '/edit') }}" title="Edit Report"><button
                class="btn btn-primary btn-sm"><i class="fa fa-edit" aria-hidden="true"></i>
                Edit</button></a>
            @if($report->trashed())
              {!! Form::open([
                'method' => 'PUT',
                'url' => ['/admin/reports/restore', $report->id],
                'style' => 'display:inline',
            ]) !!}
              {!! Form::button('<i class="fas fa-trash-restore-alt" aria-hidden="true"></i> Restore', [
                  'type' => 'submit',
                  'class' => 'btn btn-outline-danger btn-sm',
                  'title' => 'Restore Report',
                  'onclick' => 'return confirm("Confirm restore?")',
              ]) !!}
              {!! Form::close() !!}
            @else
            {!! Form::open([
                'method' => 'DELETE',
                'url' => ['admin/reports', $report->id],
                'style' => 'display:inline',
            ]) !!}
            {!! Form::button('<i class="fa fa-trash" aria-hidden="true"></i> Delete', [
                'type' => 'submit',
                'class' => 'btn btn-danger btn-sm',
                'title' => 'Delete Report',
                'onclick' => 'return confirm("Confirm delete?")',
            ]) !!}
            {!! Form::close() !!}
            @endif
            <br />
            <br />

            <h4>General info</h4>

            <div class="row">
              <div class="col-md-4">
                <i>{{ __('Customer') }}:</i>
                <b>{{ $report->customer }}</b>
              </div>
              <div class="col-md-4">
                <i>{{ __('Bill To') }}:</i>
                <b>{{ $report->client }}</b>
              </div>
              <div class="col-md-4">
                <i>{{ __('Report ID') }}:</i>
                <b>{{ $report->number }}</b>
              </div>
              @if($report->number_type === $report::TYPE_RECEIVER)
                <div class="col-md-4">
                  <i>{{ __('Rcvd Date') }}:</i>
                  <b>{{ $report->rcvd_date ? $report->rcvd_date->format('m.d.Y') : '---' }}</b>
                </div>
              @else
                <div class="col-md-4">
                  <i>{{ __('Service Date') }}:</i>
                  <b>{{ $report->wash_date ? $report->wash_date->format('m.d.Y') : '---' }}</b>
                </div>
              @endif
              <div class="col-md-4">
                <i>{{ __('Inspector') }}:</i>
                <b>{{ $report->inspector }}</b>
              </div>
              @if($report->off_lease)
                <div class="col-md-4">
                  <i>{{ __('Off Lease') }}:</i>
                  <b>Yes</b>
                </div>
              @endif
              @if($report->notes)
                <div class="col-md-12">
                  <i>{{ __('Notes') }}:</i> {{ $report->notes }}
                </div>
              @endif
              <br><br>
            </div>
            <div class="report-items">
              <div class="row">
              @if ($report->items()->count())
                <div class="col-md-12">
                  <h4>Report items (Containers)</h4>
                </div>
                <div class="col-md-12" style="overflow-y: auto; margin-top: 1rem">
                  <table class="table table-striped report-items-table">
                    <thead>
                      <tr>
                        <th></th>
                        <th>{{ __('Manufacturer') }}</th>
                        <th>{{ __('Serial #') }}</th>
                        <th>{{ __('Unit #') }}</th>
                        <th>{{ __('From report') }}</th>
                        <th>{{ __('QD') }}</th>
                        <th>{{ __('5YT') }}</th>
                        <th>{{ __('Mfr Date') }}</th>
                        <th>{{ __('30mo Retest Date') }}</th>
                        <th>{{ __('DOT/UN') }}</th>
                        <th>{{ __('Capacity') }}</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      @foreach ($report->items as $item)
                        <tr class="{{ $item->trashed() ? 'reports-table__trash-row' : '' }}">
                          <td>
                            {{ $loop->iteration }}

                            @if($item->has_certificate)
                              <span class="report-items__certificate-tooltip">
                                <i class="far fa-file-alt" data-toggle="tooltip" data-placement="bottom" title="With certification"></i>
                              </span>
                            @endif
                          </td>
                          <td>{{ $item->manufacturer }}</td>
                          <td>{{ $item->serial_number }}</td>
                          <td>{{ $item->unit_number }}</td>
                          <td>{{ $item->origin_report_number }}</td>
                          <td>{{ $item->qdLabel }}</td>
                          <td>{{ $item->get5yt() ? $item->get5yt()->format('m.Y') : '---' }}</td>
                          <td>{{ $item->mfr_date ? $item->mfr_date->format('m.Y') : '---' }}</td>
                          <td>{{ $item->ret_date ? $item->ret_date->format('m.Y') : '---' }}</td>
                          <td>{{ $item->dot_un }}</td>
                          <td>{{ $item->size }}</td>
                          <td class="actions">
                            <a href="{{ url('/admin/report-items/' . $item->id) }}" title="View Report"><button
                              class="btn btn-outline-info btn-sm"><i class="fa fa-eye" aria-hidden="true"></i></button></a>
                            <a href="{{ url('/admin/report-items/' . $item->id . '/edit') }}" title="Edit Report"><button
                              class="btn btn-primary btn-sm"><i class="fa fa-edit" aria-hidden="true"></i></button></a>
                            @if(!$report->trashed())
                              @if($item->trashed())
                                  {!! Form::open([
                                      'method' => 'PUT',
                                      'url' => ['/admin/report-items/restore', $item->id],
                                      'style' => 'display:inline',
                                  ]) !!}
                                  {!! Form::button('<i class="fas fa-trash-restore-alt" aria-hidden="true"></i>', [
                                    'type' => 'submit',
                                    'class' => 'btn btn-outline-danger btn-sm',
                                    'title' => 'Restore Report',
                                    'onclick' => 'return confirm("Restore Report?")',
                                  ]) !!}
                                {!! Form::close() !!}
                              @else
                                {!! Form::open([
                                    'method' => 'DELETE',
                                    'url' => ['/admin/report-items', $item->id],
                                    'style' => 'display:inline',
                                ]) !!}
                                {!! Form::button('<i class="fa fa-trash" aria-hidden="true"></i>', [
                                    'type' => 'submit',
                                    'class' => 'btn btn-danger btn-sm',
                                    'title' => 'Delete Report',
                                    'onclick' => 'return confirm("Confirm delete?")',
                                ]) !!}
                                {!! Form::close() !!}
                              @endif
                            @endif
                          </td>
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
                  <p class="p-2 border-top">
                    {{ __('Total') }}: <strong>{{ $report->items()->count() }}</strong> {{ __('containers') }}
                  </p>
                </div>
                @if($report->number_type === \App\Models\Report::TYPE_SERVICE && isset($itemsTotal))
                  <div class="col-md-12 pb-5">

                    <h4 class="my-5">Parts and service totals</h4>

                    <div class="row">

                      @foreach($itemsTotal as $key => $value)
                        <div class="col-sm-6 col-lg-4">
                          <div class="row p-2">
                            <div class="col-8 border border-right-0">{{ $key }}</div>
                            <div class="col-4 border border-left-0 text-center">{{ strlen($value) ? $value : '-' }}</div>
                          </div>
                        </div>
                      @endforeach

                    </div>
                  </div>
                @endif
              @endif
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection